(source gnu)
(source melpa)

(depends-on "auctex")
(depends-on "cdlatex")
(depends-on "diff-hl")
(depends-on "flyspell-correct")
(depends-on "latex-pretty-symbols")
(depends-on "latex-preview-pane")
(depends-on "org-bullets")
(depends-on "pallet")
(depends-on "try")
